
project:
  title: "Exploratory Data Analysis"
  author: "Keyla Vanessa Alba Molina"
  description: "Predicci贸n de Radiaci贸n Solar en el Nordeste de Brasil"
  language: es

book:
  sidebar:
    logo: figures/logo_uninorte.jpg 

book:
  title: "Predicci贸n de Radiaci贸n Solar en el Nordeste de Brasil"
  author: "Keyla Vanessa Alba Molina"
  logo: figures/logo_uninorte.jpg  

format:
  html:
    theme:
      light: cosmo
      custom: styles/custom.scss
    toc: true
    number_sections: true
    navigation_depth: 2
    code_folding: true
    favicon: images/favicon.ico

