
project:
  title: ""
  author: "Keyla Vanessa Alba Molina"
  description: ""
  language: es

book:
  sidebar:
    logo: figures/logo_uninorte.jpg 

book:
  title: "Predicción de Radiación Solar en los Estados del Noreste de Brasil Utilizando Técnicas Híbridas Basadas en Transformada Wavelet Discreta, ARIMA y Redes Neuronales Artificiales (ANN)"
  author: "Keyla Vanessa Alba Molina"
  logo: figures/renovable.jpg  

format:
  html:
    theme:
      light: cosmo
      custom: styles/custom.scss
    toc: true
    number_sections: true
    navigation_depth: 2
    code_folding: true
    favicon: figures/logo_uninorte.jpg

