
project:
  type: book

book:
  title: "Universidad del Norte"
  subtitle: "Doctorado en Ciencias Naturales"
  author: "Keyla Vanessa Alba Molina"
  date: "2025"
  language: es
  sidebar:
    logo: figures/logo_uninorte.jpg
    search: true

  chapters:
    - index.qmd
    - chapters/EDA_Lineamientos.ipynb
    - chapters/EDA.ipynb

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true
    css: styles/custom.scss
    page-footer:
      left: |
        By Keyla Vanessa Alba Molina  
        © Copyright 2025.  
        Universidad del Norte. Todos los derechos reservados.
