project:
  type: book


book:
  title: "Universidad del Norte"
  author: "Keyla Vanessa Alba Molina"
  language: es
  favicon: figures/logo_uninorte.jpg
  cover-image: figures/logo_uninorte.jpg
  sidebar:
    logo: figures/logo_uninorte.jpg
    search: true
  chapters:
    - index.qmd
    - chapters/EDA_Lineamientos.ipynb
    - chapters/EDA.ipynb
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    css: styles/custom.scss
    page-footer:
      left: |
        By Keyla Vanessa Alba Molina  
        © Copyright 2025.  
        Universidad del Norte. Todos los derechos reservados.


